services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    working_dir: /app

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"

    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
    db_data:  
