services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres_db
    env_file:
      - stack.env
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:8.2.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis_cache
    ports:
      - "6379:6379"
    env_file:
      - stack.env
  adminer:
    image: adminer
    container_name: adminer
    restart: always
  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: migrate
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
    db_data:  
    nginx_logs:
