services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - stack.env
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:8.2.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis_cache
    ports:
      - "6379:6379"
    env_file:
      - stack.env

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env.development
    container_name: migrate
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
    db_data:  
    nginx_logs:
