services:
  db:
    image: postgres:17.6
    restart: always
    shm_size: 128mb
    container_name: postgres_db
    env_file:
      - stack.env
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:8.2.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis_cache
    ports:
      - "6379:6379"
    env_file:
      - stack.env

  migrate:
    image: mateuszkurowski/swe-assessment-backend:latest
    container_name: migrate
    depends_on:
      - db
    env_file:
      - stack.env
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"

  backend:
    image: mateuszkurowski/swe-assessment-backend:latest
    restart: unless-stopped
    container_name: backend
    depends_on:
      - db
      - redis_cache
      - migrate
    env_file:
      - stack.env

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"

  nginx:
    image: mateuszkurowski/swe-assessment-frontend:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
    db_data:  
    nginx_logs:
