services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
    db_data:  
    nginx_logs:
