services:
  nginx:
    image: mateuszkurowski/swe-assessment-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  migrate:
    image: mateuszkurowski/swe-assessment-backend:latest
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"

  backend:
    image: mateuszkurowski/swe-assessment-backend:latest
    restart: unless-stopped
    depends_on:
      - db
      - migrate
    env_file:
      - ./backend/.env

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
    db_data:  
    nginx_logs:
