services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/site:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always

volumes:
    db_data:  
    nginx_logs:
