services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb

    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        uv run alembic upgrade head
      "
    restart: "no"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
    db_data:  
    nginx_logs:
