"""Initial contact table

Revision ID: 4c4ee7e905bc
Revises: 
Create Date: 2025-08-10 17:39:03.131857

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '4c4ee7e905bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
