name: Frontend Pipeline

env:
  BIOME_VERSION: "2.1.3"
  NODE_VERSION: "22.18.0"
on:
  push:

jobs:
  frontend-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: ${{ env.BIOME_VERSION }}
      - name: Run Biome
        run: biome ci .

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      # pnpm version is set in package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: |
            cwd: frontend/
            args: [--frozen-lockfile]

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Frontend
        run: pnpm run build

  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
              ${{ vars.DOCKERHUB_USERNAME }}/swe-assessment-frontend:latest
              ${{ vars.DOCKERHUB_USERNAME }}/swe-assessment-frontend:${{ github.sha }}